name: Build phar file

on:
  push:
    tags:
      - '*'

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.3 ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: |
          vendor/bin/pest

      - name: Compile phar file
        run: |
          composer install --no-dev --optimize-autoloader --no-progress --no-suggest
          make build-phar

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./builds/lina.phar
